//
//  CodeGenerator.swift
//  
//
//  Created by Michael Borgmann on 13/01/2024.
//

import Foundation

/// A protocol for code generators that produce bytecode from statements.
protocol CodeGenerator {
    
    associatedtype OpcodeType: RawRepresentable, CaseIterable where OpcodeType.RawValue == UInt8
    
    /// Generates bytecode for the given statements.
    ///
    /// - Parameters:
    ///   - statements: The expression to generate bytecode for.
    /// - Returns: A `Chunk` containing the generated bytecode.
    /// - Throws: An error of type `CodeGeneratorError` if bytecode generation fails.
    func generateByteCode(statements: [Statement]) throws -> Chunk
    
    /// Pops local variables from the scope when they go out of scope.
    ///
    /// This method removes variables that were defined in the current scope by "popping" them off the local stack.
    /// It ensures that the stack remains consistent with the scope depth and no unnecessary variables remain after exiting the scope.
    /// - Throws: Will propagate any errors encountered during the emission of bytecode (if applicable).
    func popVariablesFromScope() throws
}

/// A base class for code generators, implementing common functionality for bytecode generation.
///
/// Subclasses are expected to provide concrete implementations for specific bytecode generation.
/// This class also conforms to the `StatementVisitor` and `ExpressionVisitor` protocol
///  to handle different types of statements and epressions.
class BaseCodeGenerator<OpcodeType: RawRepresentable & CaseIterable>: CodeGenerator, ExpressionVisitor, StatementVisitor where OpcodeType.RawValue == UInt8 {

    // MARK: Properties
    
    /// The chunk to store the generated bytecode.
    var chunk: Chunk
    
    /// The line number associated with the generated bytecode.
    var line: Int?
    
    /// Represents a local variable within the current scope.
    struct Local {
        
        /// The name of the local variable.
        let name: Token
        
        /// The depth of the scope where the local variable is defined.
        var depth: Int?
    }
    
    /// A list of all local variables and their corresponding scopes.
    var locals: [Local] = []
    
    /// The current depth of the scope.
    var scopeDepth = 0
    
    // MARK: Lifecycle
    
    /// Initializes the code generator with a given chunk.
    ///
    /// - Parameter chunk: The chunk to store the generated bytecode.
    init(with chunk: Chunk) {
        self.chunk = chunk
    }
    
    // MARK: Actions
    
    /// Generates bytecode for the given statements.
    ///
    /// This method is meant to be overridden by subclasses.
    ///
    /// - Parameter statements: The statements to generate bytecode for.
    /// - Returns: A `Chunk` containing the generated bytecode.
    /// - Throws: An error of type `CodeGeneratorError.methodNotOverridden` if the method is not overridden.
    func generateByteCode(statements: [Statement]) throws -> Chunk {
        fatalError("Method should be overridden by subclasses")
    }
    
    // MARK: Helper
    
    /// Emits a sequence of bytes into the chunk, associating each byte with the current line number.
    ///
    /// This method writes each byte in the provided sequence to the chunk, using the current line number.
    /// If the line number is not available (i.e., `line` is `nil`), an error is thrown.
    ///
    /// - Parameter bytes: The bytes to emit into the chunk.
    /// - Throws:
    ///   - `CodeGeneratorError.unknownLine`: If the line number is not known (`line` is `nil`).
    func emitBytes(_ bytes: UInt8...) throws {
        
        guard let currentLine = line else {
            throw CodeGeneratorError.unknownLine(bytes: Array(bytes))
        }
        
        for byte in bytes {
            try chunk.write(byte: byte, line: currentLine)
        }
    }
    
    /// Executes a given statement by accepting the current visitor.
    ///
    /// - Parameter statement: The statement to execute.
    /// - Throws: Propagates errors encountered during visitor execution.
    func execute(_ statement: Statement) throws {
        try statement.accept(visitor: self)
    }
    
    /// Evaluates an expression using the provided visitor.
    ///
    /// - Parameter expression: The expression to evaluate.
    /// - Returns: The result of the expression evaluation.
    /// - Throws: An error of type `CodeGeneratorError.expressionEvaluationFailed` if evaluation fails.
    func evaluate(_ expression: Expression) throws -> Any? {
        try expression.accept(visitor: self)
    }
    
    /// Increments the current scope depth to begin a new scope.
    ///
    /// This method is typically called at the start of a block, function, or any scope that introduces new local variables.
    /// It increases the depth of the scope, enabling proper tracking and management of local variables.
    func beginScope() {
        scopeDepth += 1
    }
    
    /// Decrements the current scope depth and pops local variables that are out of scope.
    ///
    /// This method is typically called at the end of a block, function, or any scope that finishes its execution.
    /// It reduces the scope depth and ensures that any local variables defined within the scope are removed (popped) from the stack.
    /// - Throws: Will propagate errors from `popVariablesFromScope()` if popping the variables fails.
    func endScope() throws {
        try popVariablesFromScope()
        scopeDepth -= 1
    }
    
    /// Pops local variables from the scope when they go out of scope.
    ///
    /// This method removes variables that were defined in the current scope by "popping" them off the local stack.
    /// It ensures that the stack remains consistent with the scope depth and no unnecessary variables remain after exiting the scope.
    /// - Throws: Will propagate any errors encountered during the emission of bytecode (if applicable).
    func popVariablesFromScope() throws {
        fatalError("Method should be overridden by subclasses")
    }
    
    // MARK: Expression Visitor
    
    /// Visits a literal expression.
    ///
    /// This method is meant to be overridden by subclasses.
    ///
    /// - Parameter expression: The literal expression to visit.
    /// - Returns: The result of the literal expression evaluation.
    /// - Throws: An error of type `CodeGeneratorError.methodNotOverridden` if the method is not overridden.
    func visitLiteralExpr(_ expression: LiteralExpression) throws -> Any? {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits a grouping expression.
    ///
    /// This method is meant to be overridden by subclasses.
    ///
    /// - Parameter expression: The grouping expression to visit.
    /// - Returns: The result of the grouping expression evaluation.
    /// - Throws: An error of type `CodeGeneratorError.methodNotOverridden` if the method is not overridden.
    func visitGroupingExpr(_ expression: GroupingExpession) throws -> Any? {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits a unary expression.
    ///
    /// This method is meant to be overridden by subclasses.
    ///
    /// - Parameter expression: The unary expression to visit.
    /// - Returns: The result of the unary expression evaluation.
    /// - Throws: An error of type `CodeGeneratorError.methodNotOverridden` if the method is not overridden.
    func visitUnaryExpr(_ expression: UnaryExpression) throws -> Any? {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits a binary expression.
    ///
    /// This method is meant to be overridden by subclasses.
    ///
    /// - Parameter expression: The binary expression to visit.
    /// - Returns: The result of the binary expression evaluation.
    /// - Throws: An error of type `CodeGeneratorError.methodNotOverridden` if the method is not overridden.
    func visitBinaryExpr(_ expression: BinaryExpression) throws -> Any? {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits a variable expression.
    ///
    /// - Parameter expression: The variable expression to visit.
    /// - Returns: The result of the variable expression evaluation.
    /// - Throws: `CodeGeneratorError.methodNotOverridden` if not overridden by subclasses.
    func visitVariableExpr(_ expression: VariableExpression) throws -> Any? {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits an assignment expression.
    ///
    /// - Parameter expression: The assignment expression to visit.
    /// - Returns: The result of the assignment expression evaluation.
    /// - Throws: `CodeGeneratorError.methodNotOverridden` if not overridden by subclasses.
    func visitAssignExpr(_ expression: AssignExpression) throws -> Any? {
        fatalError("Method should be overridden by subclasses")
    }
    
    // MARK: Statement Visitor
    
    /// Visits a print statement.
    ///
    /// - Parameter stmt: The print statement to visit.
    /// - Throws: `CodeGeneratorError.methodNotOverridden` if not overridden by subclasses.
    func visitPrintStmt(_ stmt: Print) throws -> () {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits an expression statement.
    ///
    /// - Parameter stmt: The expression statement to visit.
    /// - Throws: `CodeGeneratorError.methodNotOverridden` if not overridden by subclasses.
    func visitExpressionStmt(_ stmt: ExpressionStmt) throws -> () {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits a variable statement.
    ///
    /// - Parameter stmt: The variable statement to visit.
    /// - Throws: `CodeGeneratorError.methodNotOverridden` if not overridden by subclasses.
    func visitVarStmt(_ stmt: VariableStatement) throws -> () {
        fatalError("Method should be overridden by subclasses")
    }
    
    /// Visits a block statement and manages scope transitions.
    ///
    /// This method starts a new scope by calling `beginScope()`, executes the statements within the block, and then ends the scope with `endScope()`.
    /// It ensures that any local variables within the block are properly scoped and cleaned up.
    /// - Parameter stmt: The block statement to visit, containing a list of statements to be executed.
    /// - Throws: Propagates any errors encountered during the execution of statements or scope management.
    func visitBlockStmt(_ stmt: BlockStatement) throws -> () {
        
        beginScope()
        
        defer {
            do {
                try endScope()
            } catch {
                assertionFailure("Failed to end scope: \(error)")
            }
        }
        
        try stmt.statements.forEach { statement in
            try execute(statement)
        }
    }
}
